config/routes.rb
CoinpostCom::Application.routes.draw do

  devise_for :users, :skip => [:sessions, :registrations]

  devise_scope :user do
    resource :registration, 
      :only => [:new, :create, :edit, :update], 
      :path => 'users',
      :path_names => { :new => 'sign_up' },
      :controller => 'registrations',
      :as => :user_registration do
      get :cancel
    end
  end

  as :user do
    get 'sign-in' => 'devise/sessions#new', :as => :new_user_session
    post 'sign-in' => 'devise/sessions#create', :as => :user_session
    delete 'sign-out' => 'devise/sessions#destroy', :as => :destroy_user_session

    # Cucumber can't seem to send delete requests, so we define this as
    # get in test mode:
    get 'sign-out' => 'devise/sessions#destroy' if Rails.env.test?
  end

  resources :users, :only => :show do

    resources :messages, :only => [:show, :create, :new ] do
      member do
        get  'reply' => 'messages#reply'
        post 'reply' => 'messages#create_reply'
      end
    end

    collection do
      # Message related
      get ':user_id/inbox' => 'messages#inbox', :as => :messages_inbox
      get ':user_id/trashed-messages' => 'messages#trash', :as => :messages_trash
      get ':user_id/sent-messages' => 'messages#sentbox',  :as => :messages_sentbox

      post ':user_id/trash-messages' => 'messages#trash_messages', 
        :as => :trash_messages
      post ':user_id/untrash-messages' => 'messages#untrash_messages', 
        :as => :untrash_messages
      
      # Payment related
      get ':user_id/sales/unfulfilled' => 'purchases#unfulfilled',
        :as => :sales_unfulfilled
      get ':user_id/sales' => 'purchases#fulfilled',
        :as => :sales_fulfilled
      get ':user_id/purchases/unpaid' => 'purchases#unpaid', 
        :as => :purchases_unpaid
      get ':user_id/purchases' => 'purchases#paid', :as => :purchases_paid
      get ':user_id/leave-feedback' => 'purchases#needs_feedback', :as => :needs_feedback

      post ':user_id/mark-fulfilled/:id' => 'purchases#mark_fulfilled', 
        :as => :mark_fulfilled
      post ':user_id/mark-paid/:id' => 'purchases#mark_paid', 
        :as => :mark_paid
      put ':user_id/leave-feedback/:id' => 'purchases#leave_feedback', 
        :as => :leave_feedback
    end
 
  end
  # need plural  
  get 'users/:id(.:format)' => 'users#show', :as => :users

  resources :items, :path_names => { :new => "sell" },
    :only => [:create, :edit, :update, :new, :destroy, :show ],
    :constraints => {:id => /[a-z0-9\-\_\/]+/i} do
    collection do 
      post 'preview'
      post 'add-images', :to => :add_images
      post 'sell', :to => :new # This is needed for the 'back' action submit

      # These are needed to create images on the new action
      post 'images', :to => 'item_images#create', :as => :create_image
      get  'images', :to => 'item_images#index'
      delete 'images/:id', :to => 'item_images#destroy', :as => :destroy_image
      
      # This is a hack to get capybara tests useable for deletes:
      get 'images/:id/delete', :to => 'item_images#destroy' if Rails.env.test?
    end

    member do
      post 'ask-question', :to => 'messages#create_from_item', 
        :as => 'ask_question'

      post 'submit-to-reddit', :to => :submit_to_reddit, :as => :submit_to_reddit
      post 'disable',      :to => :disable
      get 'relist',        :to => :relist,        :as => :relist
      get 'edit-images',   :to => :edit_images,   :as => :edit_images
      put 'update-images', :to => :update_images, :as => :update_images

      post 'purchase', :to => 'purchases#create', :as => :purchase

      # This is a hack to get capybara tests useable for deletes:
      get 'delete', :to => :destroy if Rails.env.test?
    end
  
    resources :item_images, :path => "images", :as => :images,
      :only => [:index, :create, :destroy]
  end

  resources :categories, :only => [:show,:index], :id =>  /[0-9a-z\-\/]+/i
  resources :dashboard,  :only => [ :index ]  do
    collection do
      get 'active-items',  :to => :active_items,  :as => :active_items 
      get 'pending-items', :to => :pending_items, :as => :pending_items
      get 'expired-items', :to => :expired_items, :as => :expired_items
    end
  end

  post 'ask-question' => 'home#ask_question', :as => :ask_question
  get 'about-us' => 'home#about_us', :as => :about_us
  get 'get-coins' => 'home#get_coins', :as => :get_coins
  get 'help' => 'home#help', :as => :help
  root :to => "home#index"
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  filter_access_to :all

  respond_to :html  

  ITEM_FINDERS = [ :pending, :active, :expired ]

  def index
    @purchase_tables = {
      :unpaid => Purchase.purchased_by(current_user).unpaid,
      :unfulfilled => Purchase.created_by(current_user).unfulfilled
    }
    
    @unread_messages = current_user.messages_in_inbox.unread

    @item_tables = Hash[ ITEM_FINDERS.collect{ |type| [type, item_finder(type)] } ]

    respond_to do |format|
      format.html { render :action => :index }
    end
  end

  ITEM_FINDERS.each do |type|
    define_method( ('%s_items' % type).to_sym ) do
      @items, @table = item_finder(type), type

      respond_with @items do |format|
        format.html { render :action => :items_listing }
      end
    end    
  end

  private
  def item_finder(type)
    finder = case type
      when :pending then Item.pending
      when :active then Item.purchaseable.order('items.expires_at ASC')
      when :expired then 
        Item.order('expires_at DESC').unpurchaseable.not_pending
    end

    finder.created_by current_user
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
  def active_header; :dashboard; end

  def block_params_left
    [ [:cell, :dashboard, :show, :user => current_user] ]
  end
end

app/views/dashboard/_item_table.html.haml
%table.table.table-striped.table-bordered.table-condensed.item_listing{:id => table_id}
  %thead
    %tr
      %th Item
      %th.sold Qty Sold
      %th.price Price
      %th.date Listed At
      %th.date Expires At
      %th.row_actions
  %tbody
    -items.each do |item|
      %tr
        %td=(permitted_to? :show, item) ? link_to(item.title, item) : item.title
        %td=item.quantity_purchased
        %td=btc_money item.price
        %td=l item.lists_at, :format => :short
        %td=l item.expires_at, :format => :short
        %td
          -if permitted_to? :edit, item
            =link_to t('.edit'), edit_item_url(item)
          -if permitted_to? :edit_images, item
            =link_to t('.edit_images'), edit_images_item_url(item)
          -if permitted_to? :destroy, item
            =link_to t('.destroy'), item, :method => :delete, 
              :data => {:confirm => t('.destroy_confirm')}
          -if permitted_to? :disable, item
            =link_to t('.disable'), disable_item_url(item), :method => :post,
              :data => {:confirm => t('.disable_confirm')}
          -if permitted_to? :relist, item
            =link_to t('.relist'), relist_item_url(item)
    - if click_for_more_url
      %tr
        %td(colspan=6)
          %span.pull-right
            =link_to t('.click_for_more'), click_for_more_url

app/views/dashboard/index.html.haml
%hr.long-hr
-if @unread_messages.length == 0 && @item_tables.merge(@purchase_tables).all?{|k,v| v.empty?}
  %p Seems like you've not got much going on at the moment. 
    
  %p This dashboard is a shortcut for :
  %ul
    %li viewing unread emails
    %li managing transactions requiring feedback
    %li managing items requiring payment 
    %li and managing items requiring fulfillment. 
  %p 
    However, it seems like you've not got much going on right now. How about taking a look 
    =link_to 'through the listings?', categories_path
  %p 
    Or, if you're thinking about becoming a seller, why not
    =link_to 'get started now?', new_item_path
-else
  %p= "Welcome, %s here's what's going on..." % current_user.name

  -if @unread_messages.length > 0
    %h3 Unread Messages
    %p= 'Displaying 5 of %s unread messages.' % @unread_messages.count
    =render 'messages/message_listing_table', 
      :messages => @unread_messages[0...5], 
      :message_count => @unread_messages.count,
      :columns => [:from, :subject, :sent_at], 
      :folder_name => t('.folder_name'),
      :click_for_more_url => messages_inbox_users_path(current_user)

  -[:unpaid, :unfulfilled].each do |table|
    - @purchases = @purchase_tables[table]
    - click_for_more_url = (table == :unpaid) ? purchases_unpaid_users_path(current_user) : sales_unfulfilled_users_path(current_user)
    -if @purchases.length > 0
      %h3=t('.%s_purchases' % table )
      %p=t '.purchase_listing', :total => @purchases.count,
        :current => (@purchases.length > 5) ? 5 : @purchases.count
      =render 'purchases/purchase_listing_table', 
        :purchases => @purchases.limit(5), 
        :columns => [:item, :purchaser, :quantity_purchased, :total_price],
        :click_for_more_url => click_for_more_url

  -[:active, :pending ].each do |table|
    - @items = @item_tables[table]
    - click_for_more_route = ('%s_items_dashboard_index_path' % table).to_sym
    -if @items.length > 0
      %h3=t('.%s_items_table' % table )
      %p=t '.item_listing', :total => @items.count,
        :current => (@items.length > 5) ? 5 : @items.count
      =render 'item_table', :items => @items.limit(5), 
        :table_id => '%s_items_table' % table,
        :click_for_more_url => self.send(click_for_more_route)

app/views/dashboard/items_listing.html.haml
%hr.long-hr
%p=t '.items_displayed', :total => @items.count
=render 'item_table', :items => @items, :click_for_more_url => nil, 
  :table_id => '%s_items_table' % @table
%p=link_to "Go Back to Dashboard", dashboard_index_path