config/routes.rb
CoinpostCom::Application.routes.draw do

  devise_for :users, :skip => [:sessions, :registrations]

  devise_scope :user do
    resource :registration, 
      :only => [:new, :create, :edit, :update], 
      :path => 'users',
      :path_names => { :new => 'sign_up' },
      :controller => 'registrations',
      :as => :user_registration do
      get :cancel
    end
  end

  as :user do
    get 'sign-in' => 'devise/sessions#new', :as => :new_user_session
    post 'sign-in' => 'devise/sessions#create', :as => :user_session
    delete 'sign-out' => 'devise/sessions#destroy', :as => :destroy_user_session

    # Cucumber can't seem to send delete requests, so we define this as
    # get in test mode:
    get 'sign-out' => 'devise/sessions#destroy' if Rails.env.test?
  end

  resources :users, :only => :show do

    resources :messages, :only => [:show, :create, :new ] do
      member do
        get  'reply' => 'messages#reply'
        post 'reply' => 'messages#create_reply'
      end
    end

    collection do
      # Message related
      get ':user_id/inbox' => 'messages#inbox', :as => :messages_inbox
      get ':user_id/trashed-messages' => 'messages#trash', :as => :messages_trash
      get ':user_id/sent-messages' => 'messages#sentbox',  :as => :messages_sentbox

      post ':user_id/trash-messages' => 'messages#trash_messages', 
        :as => :trash_messages
      post ':user_id/untrash-messages' => 'messages#untrash_messages', 
        :as => :untrash_messages
      
      # Payment related
      get ':user_id/sales/unfulfilled' => 'purchases#unfulfilled',
        :as => :sales_unfulfilled
      get ':user_id/sales' => 'purchases#fulfilled',
        :as => :sales_fulfilled
      get ':user_id/purchases/unpaid' => 'purchases#unpaid', 
        :as => :purchases_unpaid
      get ':user_id/purchases' => 'purchases#paid', :as => :purchases_paid
      get ':user_id/leave-feedback' => 'purchases#needs_feedback', :as => :needs_feedback

      post ':user_id/mark-fulfilled/:id' => 'purchases#mark_fulfilled', 
        :as => :mark_fulfilled
      post ':user_id/mark-paid/:id' => 'purchases#mark_paid', 
        :as => :mark_paid
      put ':user_id/leave-feedback/:id' => 'purchases#leave_feedback', 
        :as => :leave_feedback
    end
 
  end
  # need plural  
  get 'users/:id(.:format)' => 'users#show', :as => :users

  resources :items, :path_names => { :new => "sell" },
    :only => [:create, :edit, :update, :new, :destroy, :show ],
    :constraints => {:id => /[a-z0-9\-\_\/]+/i} do
    collection do 
      post 'preview'
      post 'add-images', :to => :add_images
      post 'sell', :to => :new # This is needed for the 'back' action submit

      # These are needed to create images on the new action
      post 'images', :to => 'item_images#create', :as => :create_image
      get  'images', :to => 'item_images#index'
      delete 'images/:id', :to => 'item_images#destroy', :as => :destroy_image
      
      # This is a hack to get capybara tests useable for deletes:
      get 'images/:id/delete', :to => 'item_images#destroy' if Rails.env.test?
    end

    member do
      post 'ask-question', :to => 'messages#create_from_item', 
        :as => 'ask_question'

      post 'submit-to-reddit', :to => :submit_to_reddit, :as => :submit_to_reddit
      post 'disable',      :to => :disable
      get 'relist',        :to => :relist,        :as => :relist
      get 'edit-images',   :to => :edit_images,   :as => :edit_images
      put 'update-images', :to => :update_images, :as => :update_images

      post 'purchase', :to => 'purchases#create', :as => :purchase

      # This is a hack to get capybara tests useable for deletes:
      get 'delete', :to => :destroy if Rails.env.test?
    end
  
    resources :item_images, :path => "images", :as => :images,
      :only => [:index, :create, :destroy]
  end

  resources :categories, :only => [:show,:index], :id =>  /[0-9a-z\-\/]+/i
  resources :dashboard,  :only => [ :index ]  do
    collection do
      get 'active-items',  :to => :active_items,  :as => :active_items 
      get 'pending-items', :to => :pending_items, :as => :pending_items
      get 'expired-items', :to => :expired_items, :as => :expired_items
    end
  end

  post 'ask-question' => 'home#ask_question', :as => :ask_question
  get 'about-us' => 'home#about_us', :as => :about_us
  get 'get-coins' => 'home#get_coins', :as => :get_coins
  get 'help' => 'home#help', :as => :help
  root :to => "home#index"
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  # I'm not entirely sure why this needed, but seemingly, changes to this file 
  # in dev mode, removes our overrides on the mailboxer engine.
  require_dependency 'app/engine_overrides/mailboxer' if Rails.env.development?

  [ [ :inbox, :sentbox, :trash, :create, :attribute_check => true, 
      :load_method => lambda { |c| @user = User.find params[:user_id] } ],
    [ :show, :reply, :create_reply, :attribute_check => true,
      :load_method => lambda {|c| 
        @user = User.find params[:user_id]
        raise ::Authorization::AttributeAuthorizationError unless @user == current_user

        @message = Message.find params[:id]
    } ],
    [ :trash_messages, :untrash_messages, :attribute_check => true, 
      :load_method => lambda {|c| 
        @user = User.find params[:user_id]
        raise ::Authorization::AttributeAuthorizationError unless @user == current_user

        @messages = Message.where(['id IN (?)',params[:message_ids]]).all
       
        raise ::Authorization::AttributeAuthorizationError unless (
          @messages.to_a.all?{|msg| msg.recipients.to_a.include?(@user)} )
      } ],
    [ :create_from_item, :attribute_check => true, :model => Item],
    [:all] 
  ].each{|args| filter_access_to *args }

  JSON_ACTIONS = [:create, :create_from_item]

  respond_to :html, :except => JSON_ACTIONS
  respond_to :json, :only   => JSON_ACTIONS

  def index
    messages = @user.send('messages_in_%s' % action_name)
    @message_count = messages.count
    @messages = messages.page params[:page]
    respond_with(@messages){ |format| format.html{ render } }
  end
  
  %w(inbox sentbox trash).each{ |m| alias_method m.to_sym, :index }

  def show
    current_user.read @message
    respond_with(@message){ |format| format.html{ render } }
  end

  def reply
    current_user.read @message

    @reply = Message.new :conversation_id => @message.conversation_id, 
      :subject => ('RE: %s' % @message.subject)

    respond_with(@reply){ |format| format.html{ render } }
  end

  def create_reply
    recipients = @message.recipients.uniq.reject{|u|u == current_user}

    @reply = new_message recipients, nil, 
      Conversation.find(@message.conversation_id)
    
    respond_with @reply do |format|
      if @reply.valid?
        @reply.deliver true, false # is_reply, should_clean

        flash[:notice] = t('flash.messages.reply.notice')
        format.html { redirect_to messages_inbox_users_url(current_user) }
      else
        flash[:error] = t('flash.messages.reply.alert')
        format.html { render :action => :reply }
      end
    end
  end

  def create
    @message = (action_name == 'create_from_item') ?
      new_message(@item.creator, 'Question for Item %s' % @item.title) : 
      new_message(@user)

    respond_with @message do |format|
      if @message.valid?
        @message.deliver false, false # is_reply, should_clean
        format.json { render :json => true }
      else
        format.json do
          render :json => {:errors => @message.errors}, :status => 422
        end
      end
    end
  end

  alias_method :create_from_item, :create

  # Despite the method name, note that this handles the untrash action as well
  def trash_messages
    conv_action = (action_name == 'trash_messages') ? :trash : :untrash

    @messages.each{ |conv| current_user.send conv_action,  conv }

    respond_with @messages do |format|
      flash[:notice] = t('flash.messages.%s_messages.notice' % conv_action.to_s)
      
      format.html do
        redirect_to (conv_action == :trash) ? 
          messages_inbox_users_url(current_user) :
          messages_trash_users_url(current_user)
      end
    end
  end
  
  alias_method :untrash_messages, :trash_messages

  private

  def new_message(recipients, subject = nil, conversation = nil)
    subject ||= params[:message][:subject]
    conversation ||= Conversation.new :subject => subject

    Message.new :sender => current_user,
      :body         => params[:message][:body],
      :subject      => subject,
      :conversation => conversation,
      :recipients   => (recipients.kind_of? Array) ? recipients : [recipients]
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
  def active_header; :dashboard; end

  def block_params_left
    [ [:cell, :dashboard, :show, :user => current_user] ]
  end

  def title_params
    {:subject => @message.subject } if @message
  end
    
  def resource_assets
    [tinymce_assets] if %w( reply send_reply ).include? action_name
  end

  def link_to_message_folder(msg, t_key = nil)
    folder, url = nil, nil
    if msg.sender == current_user
      folder, url = 'Sent Items', messages_sentbox_users_path(current_user)
    else
      if msg.is_trashed? current_user
        folder, url = 'Trashed Messages', messages_trash_users_path(current_user)
      else
        # Inbox
        folder, url = 'Inbox', messages_inbox_users_path(current_user)
      end
    end

    link_to (t_key) ? t(t_key, :folder_name => folder) : folder, url
  end

end

app/views/messages/_message_listing_table.html.haml
-show_select = (local_assigns.has_key?(:table_actions) && table_actions.length > 0)
- unless local_assigns.try(:[],:click_for_more_url)
  .row
    .span6.pull-left
      =t '.message_count_teaser', :count => message_count, :mail_folder => folder_name

    - if local_assigns.has_key? :table_actions
      .span3.pull-right
        -if table_actions.include? :trash
          %button.pull-right.btn.btn-danger(type = 'submit')
            %i.icon-trash.icon-white
            =t '.trash_selected'
        -if table_actions.include? :untrash
          %button.pull-right.btn(type = 'submit')
            %i.icon-trash.icon-repeat
            =t '.untrash_selected'

%table{:class => ['table', 'table-striped', 'table-bordered', 'table-condensed',
'message_listing_table'], :id => '%s_messages_table' % action_name }
  %thead
    %tr
      - if show_select
        %th.select_column
      -columns.each do |col|
        %th{:class => '%s_column' % col}=col.to_s.titleize
      %th.actions_column
  %tbody
    - if messages.length == 0
      %tr
        %td.no_messages{:colspan => columns.length + 1 + (show_select ? 1 : 0)}
          There are no messages to display in this folder.
    - else
      - messages.each do |message|
        %tr{ :class => (message.is_unread?(current_user)) ? 'unread' : '' }
          - if show_select
            %td.select_column
              = check_box_tag '', message.id, false,  name: "message_ids[]"
          - columns.each do |col|
            %td{:class => '%s_column' % col}
              - case col
              - when :to
                -recipients = message.recipients.find_all{|u| u != current_user }
                = link_to recipients.first.name, recipients.first.name
              - when :from
                = link_to message.sender.name, message.sender
              - when :subject
                -if message.is_unread?(current_user)
                  %i.icon-envelope
                -if permitted_to? :show, message
                  =link_to message.subject, user_message_url(current_user,message)
                -else
                  =message.subject
              - when :sent_at
                = '%s ago' % time_ago_in_words(message.created_at)
          %td.actions_column
            -if permitted_to? :show, message
              =link_to t('.show'), user_message_url(current_user, message), 
                :class => 'btn btn-mini btn-primary'
            -if permitted_to? :reply, message
              =link_to t('.reply'), reply_user_message_url(current_user, message), 
                :class => 'btn btn-mini'
    - if local_assigns.has_key? :click_for_more_url
      %tr
        %td(colspan=6)
          %span.pull-right
            =link_to 'Click here for more messages', click_for_more_url
- unless local_assigns.try(:[],:click_for_more_url)
  =paginate messages

app/views/messages/_show_message.html.haml
%table{ :class => [ 'table', 'table-bordered', 'table-condensed', 
  'message_%s_table' % table_class ].join(' ') }
  %thead
    %tr
      %td.first_col
        %strong From:
      %td
        -if message.sender == current_user
          = message.sender.name
        -else 
          =link_to message.sender.name, message.sender
    %tr
      %td.first_col
        %strong To:
      %td
        - to_user = message.recipients.find{|u| u != message.sender }
        -if to_user == current_user
          = to_user.try(:name)
        -else 
          =link_to to_user.try(:name), to_user
    %tr
      %td.first_col
        %strong Sent:
      %td
        = '%s (%s ago)' % [message.created_at.to_s(:long),
          time_ago_in_words(message.created_at)]
    %tr
      %td.first_col
        %strong Location:
      %td=link_to_message_folder message
    %tr.message_body
      %td.first_col 
        %strong Message:
      %td
        =raw message.body

app/views/messages/inbox.html.haml
%hr.long-hr
#inbox-message-container
  = form_tag trash_messages_users_path(current_user) do
    =render 'message_listing_table', 
      :messages => @messages, 
      :message_count => @message_count,
      :table_actions => [:trash],
      :columns => [:from, :subject, :sent_at], 
      :folder_name => t('.folder_name')

app/views/messages/reply.html.haml
=link_to_message_folder @message, '.back_to_folder'

%h2 Previous Message:
.well
  =render 'show_message', :message => @message, :table_class => 'reply'
%hr

%h2 Compose Your Response:
=tinymce_minimal
=semantic_form_for @reply, :url => reply_user_message_url do |f|
  =f.input :subject, :required => true,
    :input_html => {:class => 'input-xxlarge'}
  =f.input :body, :required => true,
    :input_html => {:class => 'tinymce input-xxlarge'}
  =f.buttons do
    =f.commit_button :reply, :label => t('formtastic.actions.reply'),
      :button_html => {:class => 'btn-primary btn-large'}
    =link_to 'Cancel',:back, :class => 'btn btn-small'

app/views/messages/sentbox.html.haml
%hr.long-hr
=render 'message_listing_table', :messages => @messages, 
  :message_count => @message_count,
  :columns => [:to, :subject, :sent_at], :folder_name => t('.folder_name')

app/views/messages/show.html.haml
%hr.long-hr
%p=link_to_message_folder @message, '.back_to_folder'

=render 'show_message', :message => @message, :table_class => 'show'

-if permitted_to? :reply, @message
  .pull-right
    =link_to t('.reply'), reply_user_message_url(current_user, @message), 
      :class => 'btn btn-large btn-primary'

app/views/messages/trash.html.haml
%hr.long-hr
#trash-message-container
  = form_tag untrash_messages_users_path(current_user), method: :post do
    =render 'message_listing_table', 
      :messages => @messages, 
      :message_count => @message_count,
      :table_actions => [:untrash], 
      :columns => [:from, :subject, :sent_at], 
      :folder_name => t('.folder_name')