config/routes.rb
CoinpostCom::Application.routes.draw do

  devise_for :users, :skip => [:sessions, :registrations]

  devise_scope :user do
    resource :registration, 
      :only => [:new, :create, :edit, :update], 
      :path => 'users',
      :path_names => { :new => 'sign_up' },
      :controller => 'registrations',
      :as => :user_registration do
      get :cancel
    end
  end

  as :user do
    get 'sign-in' => 'devise/sessions#new', :as => :new_user_session
    post 'sign-in' => 'devise/sessions#create', :as => :user_session
    delete 'sign-out' => 'devise/sessions#destroy', :as => :destroy_user_session

    # Cucumber can't seem to send delete requests, so we define this as
    # get in test mode:
    get 'sign-out' => 'devise/sessions#destroy' if Rails.env.test?
  end

  resources :users, :only => :show do

    resources :messages, :only => [:show, :create, :new ] do
      member do
        get  'reply' => 'messages#reply'
        post 'reply' => 'messages#create_reply'
      end
    end

    collection do
      # Message related
      get ':user_id/inbox' => 'messages#inbox', :as => :messages_inbox
      get ':user_id/trashed-messages' => 'messages#trash', :as => :messages_trash
      get ':user_id/sent-messages' => 'messages#sentbox',  :as => :messages_sentbox

      post ':user_id/trash-messages' => 'messages#trash_messages', 
        :as => :trash_messages
      post ':user_id/untrash-messages' => 'messages#untrash_messages', 
        :as => :untrash_messages
      
      # Payment related
      get ':user_id/sales/unfulfilled' => 'purchases#unfulfilled',
        :as => :sales_unfulfilled
      get ':user_id/sales' => 'purchases#fulfilled',
        :as => :sales_fulfilled
      get ':user_id/purchases/unpaid' => 'purchases#unpaid', 
        :as => :purchases_unpaid
      get ':user_id/purchases' => 'purchases#paid', :as => :purchases_paid
      get ':user_id/leave-feedback' => 'purchases#needs_feedback', :as => :needs_feedback

      post ':user_id/mark-fulfilled/:id' => 'purchases#mark_fulfilled', 
        :as => :mark_fulfilled
      post ':user_id/mark-paid/:id' => 'purchases#mark_paid', 
        :as => :mark_paid
      put ':user_id/leave-feedback/:id' => 'purchases#leave_feedback', 
        :as => :leave_feedback
    end
 
  end
  # need plural  
  get 'users/:id(.:format)' => 'users#show', :as => :users

  resources :items, :path_names => { :new => "sell" },
    :only => [:create, :edit, :update, :new, :destroy, :show ],
    :constraints => {:id => /[a-z0-9\-\_\/]+/i} do
    collection do 
      post 'preview'
      post 'add-images', :to => :add_images
      post 'sell', :to => :new # This is needed for the 'back' action submit

      # These are needed to create images on the new action
      post 'images', :to => 'item_images#create', :as => :create_image
      get  'images', :to => 'item_images#index'
      delete 'images/:id', :to => 'item_images#destroy', :as => :destroy_image
      
      # This is a hack to get capybara tests useable for deletes:
      get 'images/:id/delete', :to => 'item_images#destroy' if Rails.env.test?
    end

    member do
      post 'ask-question', :to => 'messages#create_from_item', 
        :as => 'ask_question'

      post 'submit-to-reddit', :to => :submit_to_reddit, :as => :submit_to_reddit
      post 'disable',      :to => :disable
      get 'relist',        :to => :relist,        :as => :relist
      get 'edit-images',   :to => :edit_images,   :as => :edit_images
      put 'update-images', :to => :update_images, :as => :update_images

      post 'purchase', :to => 'purchases#create', :as => :purchase

      # This is a hack to get capybara tests useable for deletes:
      get 'delete', :to => :destroy if Rails.env.test?
    end
  
    resources :item_images, :path => "images", :as => :images,
      :only => [:index, :create, :destroy]
  end

  resources :categories, :only => [:show,:index], :id =>  /[0-9a-z\-\/]+/i
  resources :dashboard,  :only => [ :index ]  do
    collection do
      get 'active-items',  :to => :active_items,  :as => :active_items 
      get 'pending-items', :to => :pending_items, :as => :pending_items
      get 'expired-items', :to => :expired_items, :as => :expired_items
    end
  end

  post 'ask-question' => 'home#ask_question', :as => :ask_question
  get 'about-us' => 'home#about_us', :as => :about_us
  get 'get-coins' => 'home#get_coins', :as => :get_coins
  get 'help' => 'home#help', :as => :help
  root :to => "home#index"
end

app/views/shared/_blocks.html.haml
- if blocks
  .span3
    -blocks.each do |block|
      -if block.shift == :cell
        =render_cell *block
      -else
        =render *block

app/views/shared/_buy_this_item_button.html.haml
-buy_label = raw('<i class="icon-ok icon-white"></i> Buy this Item')
-buy_options = { :class => %w(btn btn-primary btn-large buy_item_btn) }
-if user == item.creator
  =link_to buy_label, '#', buy_options.merge(:data => {:confirm => 'Sorry, but you are not permitted to purchase your own items.'})
-elsif user && item.is_purchaseable
  =link_to buy_label, '#item_purchase_modal', buy_options.merge({'data-toggle' => 'modal'})
-else
  -buy_options[:class] += ['toggle_auth_required']
  =link_to buy_label, '#', buy_options

app/views/shared/_flash.html.haml
- flash_class_map = {:error => 'alert-error',
    :alert => 'alert-info', :notice => 'alert-success'}
- flash_header_map = {:error => 'Error',
    :alert => 'Notice', :notice => 'Sucess'}
- flash.each do |name, msg|
  %div{ :class => [ 'alert', flash_class_map[name] ].join(' ') }
    %a.close(data-dismiss='alert') x
    %h4.alert-heading=flash_header_map[name]
    =raw RDiscount.new(msg).to_html if msg.is_a?(String)

app/views/shared/_footerbar.html.haml
.navbar
  .navbar-inner
    .nav-collapse
      %ul.nav
        -header_navigation.each_with_index do |nav, i|
          %li{:class => ( nav.is_active? ? 'active' : '') }
            =link_to nav.i18_label, nav.url, :class => nav.classes
      %ul.nav.pull-right
        %li
          %a(href="#") 
            Back to top
            %img{:src => '/images/back-to-top.png', :height => '8', :alt => 'Back to Top'}

app/views/shared/_headerbar.html.haml
.navbar
  .navbar-inner
    .container
      =link_to image_tag('/images/logo.png', :size => '323x78', :alt => "CoinPost Logo"), root_path, :class => "brand"
      .nav-collapse
        %div#nav-wrapper.clearfix
          %ul#main-nav.nav
            -header_navigation.each_with_index do |nav, i|
              %li{:class => ( nav.is_active? ? 'active' : '') }
                =link_to nav.i18_label, nav.url, :class => nav.classes
          %ul#user-options.nav.pull-right
            -if user_signed_in?
              %li{:class => ['dropdown',
                (@active_header_label == :dashboard) ? 'active' : nil].compact.join(' ')}
                %a(href="#" class="dropdown-toggle" data-toggle="dropdown")
                  Your Coinpost
                  %b.caret
                %ul.dropdown-menu
                  %li=link_to t('layout.header.view_dashboard'), 
                    dashboard_index_path
                  %li.divider
                  %li=link_to 'View Your Inbox',  messages_inbox_users_path(current_user)
                  %li=link_to 'Leave Feedback', needs_feedback_users_url(current_user) 
                  %li=link_to 'Manage Purchases', purchases_unpaid_users_path(current_user) 
                  %li=link_to 'Manage Sales', sales_unfulfilled_users_path(current_user) 
                  %li=link_to 'Manage Postings',active_items_dashboard_index_path
                  %li.divider
                  %li=link_to t('layout.header.sign_out'), 
                      destroy_user_session_path, :method=>'delete'
            -else
              %li=link_to t('layout.header.sign_in'), '#login_modal', 'data-toggle' => 'modal'
        
        %ul#conversion-info
          -if user_signed_in?
            %li.welcome-user
              =link_to t('layout.header.welcome_user', :username => current_user.name), 
               dashboard_index_path
          %li.conversion
            =link_to btc_to_currency_header, '#', :rel => 'tooltip', 
              'data-placement' => 'left', :class => 'exchange_rate',
              'data-original-title' => t('.exchange_rate_notice')
            -if request.get?
              .btn-group.bootstrap-select
                %button#user_preffered_currency.btn.dropdown-toggle(data-toggle="dropdown" href="#")
                  =currency_option_label(user_currency).html_safe
                  %span.caret
                .dropdown-menu
                  %ul
                    -supported_currencies.each do |iso_code|
                      -unless iso_code == user_currency
                        %li
                          =link_to currency_option_label(iso_code).html_safe, 
                            url_for(params.merge({:user_currency => iso_code})),
                            :tabindex => "-1"
            -else
              %button#user_preffered_currency.btn.disabled(href="#")
                =currency_option_label(user_currency).html_safe
                %span.caret

- if (action_name == 'index' && controller_name == 'home')               
  .hero-unit
    %div.contents
      %h2 Your Bitcoin Marketplace 
      %p Take part in the Bitcoin revolution! Start listing your products and services for sale, in exchange for bitcoins.
      %p
        =link_to 'Learn More', about_us_path, :class => %w(btn btn-primary btn-large)

app/views/shared/_ie8less.html.haml
#ie8less-container
  %p
    You are using an older version of
    %strong Internet Explorer. 
    Please 
    =link_to 'update your browser.', 'http://www.updateyourbrowser.net/en/'

app/views/shared/_item_purchase_modal.html.haml
.modal.hide.fade{'data-keyboard' => 'false', 'data-backdrop' => 'static', :id => 'item_purchase_modal'}
  =semantic_form_for purchase, :url => purchase_item_url(item), :remote => true,
    :html => {:class => 'purchase_create'} do |f|
    .modal-header
      %button.close{'data-dismiss' => 'modal' } ×
      %h3 Let's buy this item
    .modal-body
      .modal-body_form
        .row-fluid 
          .span2
            =image_tag '/images/warning.png', :alt => 'Question?',
              :size => '64x64'
          .span10
            %h3= 'Do you want to buy "%s"?' % item.title
            %ul 
              %li There is no cancelling this action
              %li Your reputation will be affected by this decision 
            =f.input :quantity_purchased, :required => true, :default => 1,
              :label => "How many do you wish to purchase? (%s Available) " % [item.quantity_available],
              :input_html => {:class => 'input-mini'}
            %p
              %strong Once you click the buy button, you are committing to this purchase.
      .modal-body_success.hide
        .row-fluid 
          .span2
            =image_tag '/images/green-checkmark.png', :alt => 'Green Checkmark',
              :size => '64x64'
          .span10
            %h3 Thank-you for your purchase!
            %p The seller has been notified of your commitment to buy. 
            %ul 
              %li Now it's time to send your coins. 
              %li Once payment is received, the seller will process your order.
            
            %h3 
              Please send 
              %span.purchase_total=btc_money( Money.new(0, Money.default_currency) )
              to: 
            %h4.btc_receive_address=item.btc_receive_address
            %p A copy of this message will be e-mailed to you. You can view the status of this transaction in your dashboard.
    .modal-footer
      =f.buttons do
        =image_tag '/images/loading.gif', :size => '32x32', 
          :alt => 'Loading', :class => 'loading_indicator'
        =link_to 'Cancel','#', :class => 'btn btn-large cancel',
          'data-dismiss' => 'modal'
        =f.commit_button :send_message, :label => t('formtastic.actions.buy'),
          :button_html => {:class => 'btn-success btn-large'}
      .close_actions.hide
        =link_to 'Ok, Great!',item_path(item), :class => 'btn'

app/views/shared/_login_modal.html.haml
.modal.hide.fade{'data-keyboard' => 'false', 'data-backdrop' => 'static', :id => 'login_modal'}
  .modal-header
    %button.close{'data-dismiss' => 'modal' } ×
    %h3.sign_in_or_create Sign-in or Create an Account
    %h3.create_account.hidden Let's Create an Account?
    %h3.account_required.hidden The feature you're trying to access requires an account
  .modal-body
    .modal-body_login
      .row-fluid
        .span6.have_an_account
          =semantic_form_for User.new, :url => user_session_path, :remote => true,
            :namespace => 'session', :html => {:id => 'user_login_form'} do |f|
            %h3 Have an account?
            =f.input :email, :required => true, :input_html => {:class => 'input-large'},
              :label => "E-Mail Address:"
            =f.input :password, :required => true, :input_html => {:class => 'input-large'},
              :label => "Password:"
            %label.checkbox
              =check_box_tag 'user[remember_me]'
              Remember Me
            =f.buttons do
              =f.commit_button :login, :label => "Sign-in",
                :button_html => {:class => 'btn-primary'}
              =image_tag '/images/loading.gif', :size => '32x32', 
                :alt => 'Loading', :class => 'loading_indicator'
            = link_to "Forgot your password?", '#', :id => 'forgot_password_link'
        .span6.hidden.forgot_password
          =semantic_form_for User.new, :url => user_password_path, :remote => true, 
            :namespace => 'password', :html => { :id => 'forgot_password_form' } do |f|
            %h3 Forgot your password?
            %p That's OK, we can e-mail you a password reset link.
            =f.input :email, :required => true, :input_html => {:class => 'input-large'},
              :label => "E-Mail Address:"
            =f.buttons do
              =f.commit_button :email_instructions, :label => "E-mail me a reset link",
                :button_html => {:class => 'btn-primary'}
              =image_tag '/images/loading.gif', :size => '32x32', 
                :alt => 'Loading', :class => 'loading_indicator'
            = link_to "Oh wait, I remember my password", '#', :id => 'remember_password_link'
        .span6.dont_have_account
          %h3 Don't have an account?
          %p We can fix that. Membership is <strong>completely free</strong>, and easy. 
          %p Check out the benefits: 
          %ul
            %li List items for sale
            %li Purchase items from others
            %li Communicate with other users
          =link_to 'Create an Account', '#', :class => 'btn btn-primary', 
            :id => 'create_account_btn'
          %p (We'll do it right here in this window)
    .modal-body_create.hidden
      =semantic_form_for User.new, :url => user_registration_path, :remote => true,
        :html => { :id => 'create_user' } do |f|
        =f.input :name, :required => true, :label => 'Pick a Username:',
          :placeholder => "Doesn't have to be your real name",
          :input_html => {:class => 'input-xlarge'}
        =f.input :email, :required => true, :input_html => {:class => 'input-xlarge'},
          :label => "Your e-mail address:"
        =f.input :location,
          :placeholder => 'Any approximation will work',
          :label => "Where are you located? (Optional):",
          :input_html => {:class => 'input-xlarge'}
        =f.input :password, :required => true, 
          :label => "Choose a password:",
          :placeholder => 'Six characters, minimum',
          :input_html => {:class => 'input-xlarge', :autocomplete => 'off'}
        =f.input :password_confirmation, :required => true, 
          :label => "Confirm your password:",
          :placeholder => 'Six characters, minimum',
          :input_html => {:class => 'input-xlarge', :autocomplete => 'off'}
        #user_captcha_input.clearfix.required.control-group
          %label(for = 'recaptcha_response_field') Tell us, are you a human?*
          .input
            #create_account_captcha
        =f.buttons do
          =f.commit_button 'Create my Account',
            :button_html => {:class => 'btn-primary btn-large'}
          =image_tag '/images/loading.gif', :size => '32x32', 
            :alt => 'Loading', :class => 'loading_indicator'
        = link_to "Oh wait, I do have an account", '#', :id => 'back_to_login'
    .modal-body_password_reset_sent.hidden
      %h3 Password Reset Instructions Sent
      %p An e-email has been sent to the provided e-mail address. 
      %p
        Click on the provided link, and you will be redirected back to CoinPost 
        and will be given the chance to reset your CoinPost password to a new one. 
      %p (Try to remember it this time!)
      %a.btn.btn-primary.btn-large{'href' => '#', 'data-dismiss' => 'modal' } Ok, Great!
    .modal-body_created_user.hidden
      %h3 User Account Created Successfully
      %p However you must verify your e-mail address before you can continue.
      %p 
        An e-email has been sent to the e-mail address you provided. Inside this
        e-mail is a link, which you must click on in order for your account to
        be enabled.
      %p 
        Once you click on verification link in your e-mail, you can begin to post
        and buy items on coinpost.com.
      %a.btn.btn-primary.btn-large{'href' => '#', 'data-dismiss' => 'modal' } Ok, Great!

app/views/shared/_message_modal.html.haml
.modal.hide.fade{'data-keyboard' => 'false', 'data-backdrop' => 'static', :id => modal_id}
  =semantic_form_for message, :url => url, :remote => true, 
    :html => {:class => 'message_create'} do |f|
    .modal-header
      %button.close{'data-dismiss' => 'modal' } ×
      %h3=title
    .modal-body
      .modal-body_form= render msg_form,
        ((local_assigns.has_key?(:msg_form_params)) ? msg_form_params : {} ).merge({:form => f})
      .modal-body_success.hide
        .row-fluid 
          .span2
            =image_tag '/images/green-checkmark.png', :alt => 'Green Checkmark',
              :size => '64x64'
          .span10
            %h3 Your Message was sent Successfully
            %p This message was placed in your Sent Items. When the seller responds to this message, their answer will arrive in your CoinPost Inbox (and you will receive a notification via e-mail).
    .modal-footer
      =f.buttons do
        =image_tag '/images/loading.gif', :size => '32x32', 
          :alt => 'Loading', :class => 'loading_indicator'
        =link_to 'Cancel','#', :class => 'btn btn-small cancel',
          'data-dismiss' => 'modal'
        =f.commit_button :send_message, :label => commit_label,
          :button_html => {:class => 'btn-primary'}
      .close_actions.hide
        =link_to 'Ok, Thanks!','#', :class => 'btn btn-small', 
          'data-dismiss' => 'modal'