config/routes.rb
CoinpostCom::Application.routes.draw do

  devise_for :users, :skip => [:sessions, :registrations]

  devise_scope :user do
    resource :registration, 
      :only => [:new, :create, :edit, :update], 
      :path => 'users',
      :path_names => { :new => 'sign_up' },
      :controller => 'registrations',
      :as => :user_registration do
      get :cancel
    end
  end

  as :user do
    get 'sign-in' => 'devise/sessions#new', :as => :new_user_session
    post 'sign-in' => 'devise/sessions#create', :as => :user_session
    delete 'sign-out' => 'devise/sessions#destroy', :as => :destroy_user_session

    # Cucumber can't seem to send delete requests, so we define this as
    # get in test mode:
    get 'sign-out' => 'devise/sessions#destroy' if Rails.env.test?
  end

  resources :users, :only => :show do

    resources :messages, :only => [:show, :create, :new ] do
      member do
        get  'reply' => 'messages#reply'
        post 'reply' => 'messages#create_reply'
      end
    end

    collection do
      # Message related
      get ':user_id/inbox' => 'messages#inbox', :as => :messages_inbox
      get ':user_id/trashed-messages' => 'messages#trash', :as => :messages_trash
      get ':user_id/sent-messages' => 'messages#sentbox',  :as => :messages_sentbox

      post ':user_id/trash-messages' => 'messages#trash_messages', 
        :as => :trash_messages
      post ':user_id/untrash-messages' => 'messages#untrash_messages', 
        :as => :untrash_messages
      
      # Payment related
      get ':user_id/sales/unfulfilled' => 'purchases#unfulfilled',
        :as => :sales_unfulfilled
      get ':user_id/sales' => 'purchases#fulfilled',
        :as => :sales_fulfilled
      get ':user_id/purchases/unpaid' => 'purchases#unpaid', 
        :as => :purchases_unpaid
      get ':user_id/purchases' => 'purchases#paid', :as => :purchases_paid
      get ':user_id/leave-feedback' => 'purchases#needs_feedback', :as => :needs_feedback

      post ':user_id/mark-fulfilled/:id' => 'purchases#mark_fulfilled', 
        :as => :mark_fulfilled
      post ':user_id/mark-paid/:id' => 'purchases#mark_paid', 
        :as => :mark_paid
      put ':user_id/leave-feedback/:id' => 'purchases#leave_feedback', 
        :as => :leave_feedback
    end
 
  end
  # need plural  
  get 'users/:id(.:format)' => 'users#show', :as => :users

  resources :items, :path_names => { :new => "sell" },
    :only => [:create, :edit, :update, :new, :destroy, :show ],
    :constraints => {:id => /[a-z0-9\-\_\/]+/i} do
    collection do 
      post 'preview'
      post 'add-images', :to => :add_images
      post 'sell', :to => :new # This is needed for the 'back' action submit

      # These are needed to create images on the new action
      post 'images', :to => 'item_images#create', :as => :create_image
      get  'images', :to => 'item_images#index'
      delete 'images/:id', :to => 'item_images#destroy', :as => :destroy_image
      
      # This is a hack to get capybara tests useable for deletes:
      get 'images/:id/delete', :to => 'item_images#destroy' if Rails.env.test?
    end

    member do
      post 'ask-question', :to => 'messages#create_from_item', 
        :as => 'ask_question'

      post 'submit-to-reddit', :to => :submit_to_reddit, :as => :submit_to_reddit
      post 'disable',      :to => :disable
      get 'relist',        :to => :relist,        :as => :relist
      get 'edit-images',   :to => :edit_images,   :as => :edit_images
      put 'update-images', :to => :update_images, :as => :update_images

      post 'purchase', :to => 'purchases#create', :as => :purchase

      # This is a hack to get capybara tests useable for deletes:
      get 'delete', :to => :destroy if Rails.env.test?
    end
  
    resources :item_images, :path => "images", :as => :images,
      :only => [:index, :create, :destroy]
  end

  resources :categories, :only => [:show,:index], :id =>  /[0-9a-z\-\/]+/i
  resources :dashboard,  :only => [ :index ]  do
    collection do
      get 'active-items',  :to => :active_items,  :as => :active_items 
      get 'pending-items', :to => :pending_items, :as => :pending_items
      get 'expired-items', :to => :expired_items, :as => :expired_items
    end
  end

  post 'ask-question' => 'home#ask_question', :as => :ask_question
  get 'about-us' => 'home#about_us', :as => :about_us
  get 'get-coins' => 'home#get_coins', :as => :get_coins
  get 'help' => 'home#help', :as => :help
  root :to => "home#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  filter_access_to :all
  
  JSON_ACTIONS = [:ask_question]

  respond_to :html, :except => JSON_ACTIONS
  respond_to :json, :only   => JSON_ACTIONS

  caches_action :index, :expires_in => 5.minutes, :layout => false

  def index
    @items_ending_soon = Item.purchaseable.order('items.expires_at ASC').includes(:images).limit 6
  end

  def get_coins
  end

  def about_us
  end

  def help
    @coinpost_admin = User.site_admin if current_user
  end

  # This isn't too great an implementation, but it's something for now. The logged
  # in users have a better interface.
  def ask_question
    @errors = {} 
    %w(subject body).each{ |attr|
      @errors[attr] = ["can't be blank"] if params[:message][attr].empty? }

    @errors['from_email'] = ['is an invalid email address'] unless ( 
      /^([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})$/i.match params[:message][:from_email] )

    respond_to do |format|
      if @errors.empty?
        ContactMailer.contact_us( 
          *[:from_email, :subject,:body].collect{|attr| params[:message][attr]}+
          [ request.env['HTTP_USER_AGENT'], request.env['REMOTE_ADDR'] ] 
        ).deliver

        format.json { render :json => true }
      else
        format.json { render :json => {:errors => @errors}, :status => 422 }
      end
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
  def block_params_left
    [ [:cell, :categories, :show] ]
  end

  def active_header 
    action_name.to_sym
  end

  def resource_assets
    assets = []
    assets << tinymce_assets if action_name == 'help' && current_user

    assets += %w(atom rss).collect do |feed|
      auto_discovery_link_tag( feed.to_sym, url_for(:action => :index, 
        :controller => :categories, :format => feed) )
    end

    assets
  end
end

app/views/home/about_us.html.haml
%hr.long-hr
:markdown
  CoinPost is a small, but growing company with the primary goal of facilitating 
  the use of bitcoins for everyday transactions. 
  
  We've got big plans, and a supportive community. So check back on us often for 
  new features and announcements.

  If you have a news or media request, feel free to email us at 
  [info@coinpost.com](mailto:info@coinpost.com) with details on what you're 
  looking for.

  If you're having a problem on the site, or wish to report an issue, you should 
  receive the quickest response by using the contact form on the [Need Help?](/help)
  section of our website. 

app/views/home/get_coins.html.haml
%hr.long-hr
%p 
  There are many ways to get bitcoins into a wallet for use with merchants on 
  our site. Depending on where your money is currently located. If you have US 
  Dollars...

#get-coins
  %div.clearfix
    %h3 Do you have cash in your pocket?
    %p.pull-left.span5
      We recommend using BitInstant to transfer Cash from a local bank (Chase, 
      Bank of America, Wells Fargo) into an CoinBase account. Create an account on the 
      CoinBase website for more details.
    %p.pull-right.span4
      =image_tag '/images/bitinstant.png', :size => '207x53', :alt => 'bitinstant'

  %div.clearfix
    %h3 Would you like to buy coins with your credit or debit card?
    %p.pull-left.span5 
      We recommend using the VirWox exchange to transfer cash from your credit card
      into bitcoins. Create an account on the VirWox website for more details.
    %p.pull-right.span4
      =image_tag '/images/virwox.png', :alt => 'Virtual World Exchange', :size => '200x59'

  %div.clearfix
    %h3 Would you like to transfer money right out of your bank account?
    %p.pull-left.span5 
      We reccomend a wire transfer from your bank account, into your CoinBase account.
      Create an account on the CoinBase website for more details.
    %p.pull-right.span4
      =image_tag '/images/coinbase-logo.png', :size => '207x39', :alt => 'CoinBase'

  %div.clearfix
    %h3 Would you like to buy coins using a Paypal 
    %p
      We recommend using the VirWox exchange to transfer cash from your PayPal (or 
      MoneyBookers/Skrill) into a bitcoin wallet. Create an account on the VirWox 
      website for more details.
  
  %div.clearfix
    %h3 Do you have money that's not in US Dollars?
    %p
      There are plenty of exchange providerse servicing most of the world's currencies, 
      take a look at the 
      =link_to 'Bitcoin Wiki', 'https://en.bitcoin.it/wiki/Buying_bitcoins'
      to find 

app/views/home/help.html.haml
%hr.long-hr
:markdown
  We're currently compiling a list of frequent questions so that we can add some
  immediate gratification for our visitors, to this page. Since we don't have 
  quite enough questions yet, we invite you to use the form below to ask us for 
  assistance. We're happy to answer questions about the site, bitcoins in general
  or even give you some pointers on transcendental meditation techniques. 

  If you'd rather reach us by e-mail, try us at [info@coinpost.com](mailto:info@coinpost.com).

%hr
#ask_admin_question
  %h3 Ask us a question
  -if @coinpost_admin
    =tinymce_minimal
    %p 
      Answers will arrive in your CoinPost inbox, and the email address we have on
      your account. 

    =semantic_form_for Message.new, :url => user_messages_url(@coinpost_admin),
      :remote => true, :html => {:id => 'admin_message', :class => 'message_create'} do  |f|
      =f.input :subject, :required => true, :label => 'Question',
        :input_html => {:class => 'input-xxlarge'}
      =f.input :body, :required => true,
        :input_html => {:class => 'tinymce input-xxlarge'}
      =f.buttons do
        =f.commit_button :send, :label => "Send Question",
          :button_html => {:class => 'btn-primary btn-large'}
        =image_tag '/images/loading.gif', :size => '32x32', 
          :alt => 'Loading', :class => %w(loading_indicator hidden)
  -else
    =form_tag ask_question_path, 
      {:remote => true, :id => 'admin_message', :class=> 'message_create'} do
      .string.clearfix.required.control-group.stringish#message_from_email_input
        %label(for="message_from_email")
          From (E-mail):
          %abbr(title='required') *
        .input
          =text_field_tag 'message[from_email]', nil, 
            :id => 'message_from_email', :class => 'input-xxlarge', :maxlength => 255
      .string.clearfix.required.control-group.stringish#message_subject_input
        %label(for="message_subject")
          Question
          %abbr(title='required') *
        .input
          =text_field_tag 'message[subject]', nil, 
            :id => 'message_subject', :class => 'input-xxlarge', :maxlength => 255
      .text.clearfix.required.control-group.stringish#message_body_input
        %label(for="message_body")
          Message
          %abbr(title='required') *
        .input
          = text_area_tag 'message[body]', nil, :rows => 20,  
            :id => 'message_body', :class => %w(input-xxlarge short_textfield)
      .actions
        = submit_tag 'Send Question', :class => %w(btn-primary btn-large btn commit create), 
          :name => 'commit'
        = image_tag '/images/loading.gif', :size => '32x32', 
          :alt => 'Loading', :class => %w(loading_indicator hidden)

#message_sent_successfully.hidden
  .row 
    .span1
      =image_tag '/images/green-checkmark.png', :alt => 'Green Checkmark',
        :size => '64x64'
    .span6
      %h3 Your Question was sent Successfully
      %p 
        We should be able to answer most questions within twenty-four hours. You'll
        receive a reply in your inbox when we send our response.
      =link_to 'Ask another question', '#', :id => 'repeat_question'

app/views/home/index.html.haml
%h2 Items Expiring Soon
%hr.long-hr
-@items_ending_soon.in_groups_of(2).each do |items|
  .row-fluid
    -items.compact.each do |item|
      .span6
        %h3=link_to item.title, item
        -if item.images.length > 0
          =cw_image item.images[0].image.category_listing_small, 
            :alt => item.title, :class=> 'thumbnail pull-left'
        %p='%s...' % item.listing_teaser
        %p
          =link_to "View Details", item_path(item), :class => 'btn'
          %span.price
            %strong Price:
            =btc_money item.price
=link_to 'Browse All Items', categories_path, :class => 'btn btn-primary btn-large', :id => 'browse-all-items-btn'